'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CallDataReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SerializedCall", [Namespace]:="http://schemas.datacontract.org/2004/07/HelpdeeskDataServices", IsReference:=true),  _
     System.SerializableAttribute()>  _
    Partial Public Class SerializedCall
        Inherits CallDataReference.ComplexObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CallIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateClosedField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateOpenedField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmployeeIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NotesField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OpenStatusField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProblemIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TechIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimerField() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CallID() As Integer
            Get
                Return Me.CallIDField
            End Get
            Set
                If (Me.CallIDField.Equals(value) <> true) Then
                    Me.CallIDField = value
                    Me.RaisePropertyChanged("CallID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateClosed() As System.Nullable(Of Date)
            Get
                Return Me.DateClosedField
            End Get
            Set
                If (Me.DateClosedField.Equals(value) <> true) Then
                    Me.DateClosedField = value
                    Me.RaisePropertyChanged("DateClosed")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateOpened() As Date
            Get
                Return Me.DateOpenedField
            End Get
            Set
                If (Me.DateOpenedField.Equals(value) <> true) Then
                    Me.DateOpenedField = value
                    Me.RaisePropertyChanged("DateOpened")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmployeeID() As Integer
            Get
                Return Me.EmployeeIDField
            End Get
            Set
                If (Me.EmployeeIDField.Equals(value) <> true) Then
                    Me.EmployeeIDField = value
                    Me.RaisePropertyChanged("EmployeeID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Notes() As Byte()
            Get
                Return Me.NotesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NotesField, value) <> true) Then
                    Me.NotesField = value
                    Me.RaisePropertyChanged("Notes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OpenStatus() As System.Nullable(Of Boolean)
            Get
                Return Me.OpenStatusField
            End Get
            Set
                If (Me.OpenStatusField.Equals(value) <> true) Then
                    Me.OpenStatusField = value
                    Me.RaisePropertyChanged("OpenStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProblemID() As Integer
            Get
                Return Me.ProblemIDField
            End Get
            Set
                If (Me.ProblemIDField.Equals(value) <> true) Then
                    Me.ProblemIDField = value
                    Me.RaisePropertyChanged("ProblemID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TechID() As Integer
            Get
                Return Me.TechIDField
            End Get
            Set
                If (Me.TechIDField.Equals(value) <> true) Then
                    Me.TechIDField = value
                    Me.RaisePropertyChanged("TechID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Timer() As Byte()
            Get
                Return Me.TimerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimerField, value) <> true) Then
                    Me.TimerField = value
                    Me.RaisePropertyChanged("Timer")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StructuralObject", [Namespace]:="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference:=true),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(CallDataReference.ComplexObject)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(CallDataReference.SerializedCall))>  _
    Partial Public Class StructuralObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ComplexObject", [Namespace]:="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference:=true),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(CallDataReference.SerializedCall))>  _
    Partial Public Class ComplexObject
        Inherits CallDataReference.StructuralObject
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CallDataReference.ICallDataService")>  _
    Public Interface ICallDataService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICallDataService/Update", ReplyAction:="http://tempuri.org/ICallDataService/UpdateResponse")>  _
        Function Update(ByVal bytCall() As Byte) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICallDataService/GetByID", ReplyAction:="http://tempuri.org/ICallDataService/GetByIDResponse")>  _
        Function GetByID(ByVal callid As Integer) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICallDataService/Delete", ReplyAction:="http://tempuri.org/ICallDataService/DeleteResponse")>  _
        Function Delete(ByVal callid As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICallDataService/Create", ReplyAction:="http://tempuri.org/ICallDataService/CreateResponse")>  _
        Function Create(ByVal bytCall() As Byte) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICallDataService/GetAll", ReplyAction:="http://tempuri.org/ICallDataService/GetAllResponse")>  _
        Function GetAll(ByVal [set] As String) As CallDataReference.SerializedCall()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICallDataServiceChannel
        Inherits CallDataReference.ICallDataService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CallDataServiceClient
        Inherits System.ServiceModel.ClientBase(Of CallDataReference.ICallDataService)
        Implements CallDataReference.ICallDataService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Update(ByVal bytCall() As Byte) As Integer Implements CallDataReference.ICallDataService.Update
            Return MyBase.Channel.Update(bytCall)
        End Function
        
        Public Function GetByID(ByVal callid As Integer) As Byte() Implements CallDataReference.ICallDataService.GetByID
            Return MyBase.Channel.GetByID(callid)
        End Function
        
        Public Function Delete(ByVal callid As Integer) As Integer Implements CallDataReference.ICallDataService.Delete
            Return MyBase.Channel.Delete(callid)
        End Function
        
        Public Function Create(ByVal bytCall() As Byte) As Integer Implements CallDataReference.ICallDataService.Create
            Return MyBase.Channel.Create(bytCall)
        End Function
        
        Public Function GetAll(ByVal [set] As String) As CallDataReference.SerializedCall() Implements CallDataReference.ICallDataService.GetAll
            Return MyBase.Channel.GetAll([set])
        End Function
    End Class
End Namespace
