//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpdeskBusinessUserObjects.EmployeeDataReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializedEmployee", Namespace="http://schemas.datacontract.org/2004/07/HelpdeskDataServices", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SerializedEmployee : HelpdeskBusinessUserObjects.EmployeeDataReference.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsTechField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TimerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsTech {
            get {
                return this.IsTechField;
            }
            set {
                if ((this.IsTechField.Equals(value) != true)) {
                    this.IsTechField = value;
                    this.RaisePropertyChanged("IsTech");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timer {
            get {
                return this.TimerField;
            }
            set {
                if ((object.ReferenceEquals(this.TimerField, value) != true)) {
                    this.TimerField = value;
                    this.RaisePropertyChanged("Timer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelpdeskBusinessUserObjects.EmployeeDataReference.ComplexObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelpdeskBusinessUserObjects.EmployeeDataReference.SerializedEmployee))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelpdeskBusinessUserObjects.EmployeeDataReference.SerializedEmployee))]
    public partial class ComplexObject : HelpdeskBusinessUserObjects.EmployeeDataReference.StructuralObject {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeDataReference.IEmployeeDataService")]
    public interface IEmployeeDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDataService/Create", ReplyAction="http://tempuri.org/IEmployeeDataService/CreateResponse")]
        int Create(byte[] ByteArrayEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDataService/Update", ReplyAction="http://tempuri.org/IEmployeeDataService/UpdateResponse")]
        int Update(byte[] bytEmployee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDataService/GetByID", ReplyAction="http://tempuri.org/IEmployeeDataService/GetByIDResponse")]
        byte[] GetByID(int empid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDataService/Delete", ReplyAction="http://tempuri.org/IEmployeeDataService/DeleteResponse")]
        int Delete(int empid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDataService/GetAll", ReplyAction="http://tempuri.org/IEmployeeDataService/GetAllResponse")]
        HelpdeskBusinessUserObjects.EmployeeDataReference.SerializedEmployee[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDataService/GetAllTechs", ReplyAction="http://tempuri.org/IEmployeeDataService/GetAllTechsResponse")]
        HelpdeskBusinessUserObjects.EmployeeDataReference.SerializedEmployee[] GetAllTechs();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeDataServiceChannel : HelpdeskBusinessUserObjects.EmployeeDataReference.IEmployeeDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeDataServiceClient : System.ServiceModel.ClientBase<HelpdeskBusinessUserObjects.EmployeeDataReference.IEmployeeDataService>, HelpdeskBusinessUserObjects.EmployeeDataReference.IEmployeeDataService {
        
        public EmployeeDataServiceClient() {
        }
        
        public EmployeeDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Create(byte[] ByteArrayEmp) {
            return base.Channel.Create(ByteArrayEmp);
        }
        
        public int Update(byte[] bytEmployee) {
            return base.Channel.Update(bytEmployee);
        }
        
        public byte[] GetByID(int empid) {
            return base.Channel.GetByID(empid);
        }
        
        public int Delete(int empid) {
            return base.Channel.Delete(empid);
        }
        
        public HelpdeskBusinessUserObjects.EmployeeDataReference.SerializedEmployee[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public HelpdeskBusinessUserObjects.EmployeeDataReference.SerializedEmployee[] GetAllTechs() {
            return base.Channel.GetAllTechs();
        }
    }
}
