//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HelpDeskDBModel", "FK_Calls_Employees", "Employees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HelpdeeskDataServices.Employee), "Calls", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HelpdeeskDataServices.Call), true)]
[assembly: EdmRelationshipAttribute("HelpDeskDBModel", "FK_Calls_Employees1", "Employees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HelpdeeskDataServices.Employee), "Calls", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HelpdeeskDataServices.Call), true)]
[assembly: EdmRelationshipAttribute("HelpDeskDBModel", "FK_Calls_Problems", "Problems", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HelpdeeskDataServices.Problem), "Calls", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HelpdeeskDataServices.Call), true)]
[assembly: EdmRelationshipAttribute("HelpDeskDBModel", "FK_EmployeeInDept", "Departments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HelpdeeskDataServices.Department), "Employees", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HelpdeeskDataServices.Employee), true)]

#endregion

namespace HelpdeeskDataServices
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HelpDeskDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HelpDeskDBEntities object using the connection string found in the 'HelpDeskDBEntities' section of the application configuration file.
        /// </summary>
        public HelpDeskDBEntities() : base("name=HelpDeskDBEntities", "HelpDeskDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HelpDeskDBEntities object.
        /// </summary>
        public HelpDeskDBEntities(string connectionString) : base(connectionString, "HelpDeskDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HelpDeskDBEntities object.
        /// </summary>
        public HelpDeskDBEntities(EntityConnection connection) : base(connection, "HelpDeskDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Call> Calls
        {
            get
            {
                if ((_Calls == null))
                {
                    _Calls = base.CreateObjectSet<Call>("Calls");
                }
                return _Calls;
            }
        }
        private ObjectSet<Call> _Calls;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Department> Departments
        {
            get
            {
                if ((_Departments == null))
                {
                    _Departments = base.CreateObjectSet<Department>("Departments");
                }
                return _Departments;
            }
        }
        private ObjectSet<Department> _Departments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Problem> Problems
        {
            get
            {
                if ((_Problems == null))
                {
                    _Problems = base.CreateObjectSet<Problem>("Problems");
                }
                return _Problems;
            }
        }
        private ObjectSet<Problem> _Problems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Calls EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCalls(Call call)
        {
            base.AddObject("Calls", call);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Departments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartments(Department department)
        {
            base.AddObject("Departments", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Problems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProblems(Problem problem)
        {
            base.AddObject("Problems", problem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<SerializeEmployee> ReturnAllEmployees()
        {
            return base.ExecuteFunction<SerializeEmployee>("ReturnAllEmployees");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<SerializedCall> SerializedCall()
        {
            return base.ExecuteFunction<SerializedCall>("SerializedCall");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HelpDeskDBModel", Name="Call")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Call : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Call object.
        /// </summary>
        /// <param name="callID">Initial value of the CallID property.</param>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        /// <param name="problemID">Initial value of the ProblemID property.</param>
        /// <param name="techID">Initial value of the TechID property.</param>
        /// <param name="dateOpened">Initial value of the DateOpened property.</param>
        public static Call CreateCall(global::System.Int32 callID, global::System.Int32 employeeID, global::System.Int32 problemID, global::System.Int32 techID, global::System.DateTime dateOpened)
        {
            Call call = new Call();
            call.CallID = callID;
            call.EmployeeID = employeeID;
            call.ProblemID = problemID;
            call.TechID = techID;
            call.DateOpened = dateOpened;
            return call;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CallID
        {
            get
            {
                return _CallID;
            }
            set
            {
                if (_CallID != value)
                {
                    OnCallIDChanging(value);
                    ReportPropertyChanging("CallID");
                    _CallID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CallID");
                    OnCallIDChanged();
                }
            }
        }
        private global::System.Int32 _CallID;
        partial void OnCallIDChanging(global::System.Int32 value);
        partial void OnCallIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProblemID
        {
            get
            {
                return _ProblemID;
            }
            set
            {
                OnProblemIDChanging(value);
                ReportPropertyChanging("ProblemID");
                _ProblemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProblemID");
                OnProblemIDChanged();
            }
        }
        private global::System.Int32 _ProblemID;
        partial void OnProblemIDChanging(global::System.Int32 value);
        partial void OnProblemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TechID
        {
            get
            {
                return _TechID;
            }
            set
            {
                OnTechIDChanging(value);
                ReportPropertyChanging("TechID");
                _TechID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TechID");
                OnTechIDChanged();
            }
        }
        private global::System.Int32 _TechID;
        partial void OnTechIDChanging(global::System.Int32 value);
        partial void OnTechIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOpened
        {
            get
            {
                return _DateOpened;
            }
            set
            {
                OnDateOpenedChanging(value);
                ReportPropertyChanging("DateOpened");
                _DateOpened = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOpened");
                OnDateOpenedChanged();
            }
        }
        private global::System.DateTime _DateOpened;
        partial void OnDateOpenedChanging(global::System.DateTime value);
        partial void OnDateOpenedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateClosed
        {
            get
            {
                return _DateClosed;
            }
            set
            {
                OnDateClosedChanging(value);
                ReportPropertyChanging("DateClosed");
                _DateClosed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateClosed");
                OnDateClosedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateClosed;
        partial void OnDateClosedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateClosedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OpenStatus
        {
            get
            {
                return _OpenStatus;
            }
            set
            {
                OnOpenStatusChanging(value);
                ReportPropertyChanging("OpenStatus");
                _OpenStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OpenStatus");
                OnOpenStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _OpenStatus;
        partial void OnOpenStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnOpenStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Notes
        {
            get
            {
                return StructuralObject.GetValidValue(_Notes);
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.Byte[] _Notes;
        partial void OnNotesChanging(global::System.Byte[] value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Timer
        {
            get
            {
                return StructuralObject.GetValidValue(_Timer);
            }
            set
            {
                OnTimerChanging(value);
                ReportPropertyChanging("Timer");
                _Timer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timer");
                OnTimerChanged();
            }
        }
        private global::System.Byte[] _Timer;
        partial void OnTimerChanging(global::System.Byte[] value);
        partial void OnTimerChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HelpDeskDBModel", "FK_Calls_Employees", "Employees")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HelpDeskDBModel.FK_Calls_Employees", "Employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HelpDeskDBModel.FK_Calls_Employees", "Employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HelpDeskDBModel.FK_Calls_Employees", "Employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("HelpDeskDBModel.FK_Calls_Employees", "Employees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HelpDeskDBModel", "FK_Calls_Employees1", "Employees")]
        public Employee Employee1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HelpDeskDBModel.FK_Calls_Employees1", "Employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HelpDeskDBModel.FK_Calls_Employees1", "Employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> Employee1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("HelpDeskDBModel.FK_Calls_Employees1", "Employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("HelpDeskDBModel.FK_Calls_Employees1", "Employees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HelpDeskDBModel", "FK_Calls_Problems", "Problems")]
        public Problem Problem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Problem>("HelpDeskDBModel.FK_Calls_Problems", "Problems").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Problem>("HelpDeskDBModel.FK_Calls_Problems", "Problems").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Problem> ProblemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Problem>("HelpDeskDBModel.FK_Calls_Problems", "Problems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Problem>("HelpDeskDBModel.FK_Calls_Problems", "Problems", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HelpDeskDBModel", Name="Department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="departmentID">Initial value of the DepartmentID property.</param>
        public static Department CreateDepartment(global::System.Int32 departmentID)
        {
            Department department = new Department();
            department.DepartmentID = departmentID;
            return department;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                if (_DepartmentID != value)
                {
                    OnDepartmentIDChanging(value);
                    ReportPropertyChanging("DepartmentID");
                    _DepartmentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DepartmentID");
                    OnDepartmentIDChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Int32 value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HelpDeskDBModel", "FK_EmployeeInDept", "Employees")]
        public EntityCollection<Employee> Employees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee>("HelpDeskDBModel.FK_EmployeeInDept", "Employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee>("HelpDeskDBModel.FK_EmployeeInDept", "Employees", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HelpDeskDBModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        /// <param name="departmentID">Initial value of the DepartmentID property.</param>
        /// <param name="timer">Initial value of the Timer property.</param>
        public static Employee CreateEmployee(global::System.Int32 employeeID, global::System.Int32 departmentID, global::System.Byte[] timer)
        {
            Employee employee = new Employee();
            employee.EmployeeID = employeeID;
            employee.DepartmentID = departmentID;
            employee.Timer = timer;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                if (_EmployeeID != value)
                {
                    OnEmployeeIDChanging(value);
                    ReportPropertyChanging("EmployeeID");
                    _EmployeeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeID");
                    OnEmployeeIDChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNo
        {
            get
            {
                return _PhoneNo;
            }
            set
            {
                OnPhoneNoChanging(value);
                ReportPropertyChanging("PhoneNo");
                _PhoneNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNo");
                OnPhoneNoChanged();
            }
        }
        private global::System.String _PhoneNo;
        partial void OnPhoneNoChanging(global::System.String value);
        partial void OnPhoneNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                OnDepartmentIDChanging(value);
                ReportPropertyChanging("DepartmentID");
                _DepartmentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentID");
                OnDepartmentIDChanged();
            }
        }
        private global::System.Int32 _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Int32 value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Timer
        {
            get
            {
                return StructuralObject.GetValidValue(_Timer);
            }
            set
            {
                OnTimerChanging(value);
                ReportPropertyChanging("Timer");
                _Timer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timer");
                OnTimerChanged();
            }
        }
        private global::System.Byte[] _Timer;
        partial void OnTimerChanging(global::System.Byte[] value);
        partial void OnTimerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsTech
        {
            get
            {
                return _IsTech;
            }
            set
            {
                OnIsTechChanging(value);
                ReportPropertyChanging("IsTech");
                _IsTech = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsTech");
                OnIsTechChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsTech;
        partial void OnIsTechChanging(Nullable<global::System.Boolean> value);
        partial void OnIsTechChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HelpDeskDBModel", "FK_Calls_Employees", "Calls")]
        public EntityCollection<Call> Calls
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Call>("HelpDeskDBModel.FK_Calls_Employees", "Calls");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Call>("HelpDeskDBModel.FK_Calls_Employees", "Calls", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HelpDeskDBModel", "FK_Calls_Employees1", "Calls")]
        public EntityCollection<Call> Calls1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Call>("HelpDeskDBModel.FK_Calls_Employees1", "Calls");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Call>("HelpDeskDBModel.FK_Calls_Employees1", "Calls", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HelpDeskDBModel", "FK_EmployeeInDept", "Departments")]
        public Department Department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("HelpDeskDBModel.FK_EmployeeInDept", "Departments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("HelpDeskDBModel.FK_EmployeeInDept", "Departments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("HelpDeskDBModel.FK_EmployeeInDept", "Departments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("HelpDeskDBModel.FK_EmployeeInDept", "Departments", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HelpDeskDBModel", Name="Problem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Problem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Problem object.
        /// </summary>
        /// <param name="problemID">Initial value of the ProblemID property.</param>
        public static Problem CreateProblem(global::System.Int32 problemID)
        {
            Problem problem = new Problem();
            problem.ProblemID = problemID;
            return problem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProblemID
        {
            get
            {
                return _ProblemID;
            }
            set
            {
                if (_ProblemID != value)
                {
                    OnProblemIDChanging(value);
                    ReportPropertyChanging("ProblemID");
                    _ProblemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProblemID");
                    OnProblemIDChanged();
                }
            }
        }
        private global::System.Int32 _ProblemID;
        partial void OnProblemIDChanging(global::System.Int32 value);
        partial void OnProblemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HelpDeskDBModel", "FK_Calls_Problems", "Calls")]
        public EntityCollection<Call> Calls
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Call>("HelpDeskDBModel.FK_Calls_Problems", "Calls");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Call>("HelpDeskDBModel.FK_Calls_Problems", "Calls", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HelpDeskDBModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="HelpDeskDBModel", Name="SerializedCall")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SerializedCall : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SerializedCall object.
        /// </summary>
        /// <param name="callID">Initial value of the CallID property.</param>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        /// <param name="problemID">Initial value of the ProblemID property.</param>
        /// <param name="techID">Initial value of the TechID property.</param>
        /// <param name="dateOpened">Initial value of the DateOpened property.</param>
        public static SerializedCall CreateSerializedCall(global::System.Int32 callID, global::System.Int32 employeeID, global::System.Int32 problemID, global::System.Int32 techID, global::System.DateTime dateOpened)
        {
            SerializedCall serializedCall = new SerializedCall();
            serializedCall.CallID = callID;
            serializedCall.EmployeeID = employeeID;
            serializedCall.ProblemID = problemID;
            serializedCall.TechID = techID;
            serializedCall.DateOpened = dateOpened;
            return serializedCall;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CallID
        {
            get
            {
                return _CallID;
            }
            set
            {
                OnCallIDChanging(value);
                ReportPropertyChanging("CallID");
                _CallID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CallID");
                OnCallIDChanged();
            }
        }
        private global::System.Int32 _CallID;
        partial void OnCallIDChanging(global::System.Int32 value);
        partial void OnCallIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProblemID
        {
            get
            {
                return _ProblemID;
            }
            set
            {
                OnProblemIDChanging(value);
                ReportPropertyChanging("ProblemID");
                _ProblemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProblemID");
                OnProblemIDChanged();
            }
        }
        private global::System.Int32 _ProblemID;
        partial void OnProblemIDChanging(global::System.Int32 value);
        partial void OnProblemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TechID
        {
            get
            {
                return _TechID;
            }
            set
            {
                OnTechIDChanging(value);
                ReportPropertyChanging("TechID");
                _TechID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TechID");
                OnTechIDChanged();
            }
        }
        private global::System.Int32 _TechID;
        partial void OnTechIDChanging(global::System.Int32 value);
        partial void OnTechIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOpened
        {
            get
            {
                return _DateOpened;
            }
            set
            {
                OnDateOpenedChanging(value);
                ReportPropertyChanging("DateOpened");
                _DateOpened = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOpened");
                OnDateOpenedChanged();
            }
        }
        private global::System.DateTime _DateOpened;
        partial void OnDateOpenedChanging(global::System.DateTime value);
        partial void OnDateOpenedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateClosed
        {
            get
            {
                return _DateClosed;
            }
            set
            {
                OnDateClosedChanging(value);
                ReportPropertyChanging("DateClosed");
                _DateClosed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateClosed");
                OnDateClosedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateClosed;
        partial void OnDateClosedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateClosedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OpenStatus
        {
            get
            {
                return _OpenStatus;
            }
            set
            {
                OnOpenStatusChanging(value);
                ReportPropertyChanging("OpenStatus");
                _OpenStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OpenStatus");
                OnOpenStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _OpenStatus;
        partial void OnOpenStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnOpenStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Notes
        {
            get
            {
                return StructuralObject.GetValidValue(_Notes);
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.Byte[] _Notes;
        partial void OnNotesChanging(global::System.Byte[] value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Timer
        {
            get
            {
                return StructuralObject.GetValidValue(_Timer);
            }
            set
            {
                OnTimerChanging(value);
                ReportPropertyChanging("Timer");
                _Timer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timer");
                OnTimerChanged();
            }
        }
        private global::System.Byte[] _Timer;
        partial void OnTimerChanging(global::System.Byte[] value);
        partial void OnTimerChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="HelpDeskDBModel", Name="SerializeEmployee")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SerializeEmployee : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SerializeEmployee object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        /// <param name="departmentID">Initial value of the DepartmentID property.</param>
        /// <param name="timer">Initial value of the Timer property.</param>
        public static SerializeEmployee CreateSerializeEmployee(global::System.Int32 employeeID, global::System.Int32 departmentID, global::System.Byte[] timer)
        {
            SerializeEmployee serializeEmployee = new SerializeEmployee();
            serializeEmployee.EmployeeID = employeeID;
            serializeEmployee.DepartmentID = departmentID;
            serializeEmployee.Timer = timer;
            return serializeEmployee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNo
        {
            get
            {
                return _PhoneNo;
            }
            set
            {
                OnPhoneNoChanging(value);
                ReportPropertyChanging("PhoneNo");
                _PhoneNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNo");
                OnPhoneNoChanged();
            }
        }
        private global::System.String _PhoneNo;
        partial void OnPhoneNoChanging(global::System.String value);
        partial void OnPhoneNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                OnDepartmentIDChanging(value);
                ReportPropertyChanging("DepartmentID");
                _DepartmentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentID");
                OnDepartmentIDChanged();
            }
        }
        private global::System.Int32 _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Int32 value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Timer
        {
            get
            {
                return StructuralObject.GetValidValue(_Timer);
            }
            set
            {
                OnTimerChanging(value);
                ReportPropertyChanging("Timer");
                _Timer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Timer");
                OnTimerChanged();
            }
        }
        private global::System.Byte[] _Timer;
        partial void OnTimerChanging(global::System.Byte[] value);
        partial void OnTimerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsTech
        {
            get
            {
                return _IsTech;
            }
            set
            {
                OnIsTechChanging(value);
                ReportPropertyChanging("IsTech");
                _IsTech = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsTech");
                OnIsTechChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsTech;
        partial void OnIsTechChanging(Nullable<global::System.Boolean> value);
        partial void OnIsTechChanged();

        #endregion

    }

    #endregion

    
}
