'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EmployeeDataReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SerializeEmployee", [Namespace]:="http://schemas.datacontract.org/2004/07/HelpdeeskDataServices", IsReference:=true),  _
     System.SerializableAttribute()>  _
    Partial Public Class SerializeEmployee
        Inherits EmployeeDataReference.ComplexObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartmentIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmployeeIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsTechField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PhoneNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimerField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DepartmentID() As Integer
            Get
                Return Me.DepartmentIDField
            End Get
            Set
                If (Me.DepartmentIDField.Equals(value) <> true) Then
                    Me.DepartmentIDField = value
                    Me.RaisePropertyChanged("DepartmentID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmployeeID() As Integer
            Get
                Return Me.EmployeeIDField
            End Get
            Set
                If (Me.EmployeeIDField.Equals(value) <> true) Then
                    Me.EmployeeIDField = value
                    Me.RaisePropertyChanged("EmployeeID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsTech() As System.Nullable(Of Boolean)
            Get
                Return Me.IsTechField
            End Get
            Set
                If (Me.IsTechField.Equals(value) <> true) Then
                    Me.IsTechField = value
                    Me.RaisePropertyChanged("IsTech")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PhoneNo() As String
            Get
                Return Me.PhoneNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PhoneNoField, value) <> true) Then
                    Me.PhoneNoField = value
                    Me.RaisePropertyChanged("PhoneNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Timer() As Byte()
            Get
                Return Me.TimerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimerField, value) <> true) Then
                    Me.TimerField = value
                    Me.RaisePropertyChanged("Timer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StructuralObject", [Namespace]:="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference:=true),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EmployeeDataReference.ComplexObject)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EmployeeDataReference.SerializeEmployee))>  _
    Partial Public Class StructuralObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ComplexObject", [Namespace]:="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference:=true),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EmployeeDataReference.SerializeEmployee))>  _
    Partial Public Class ComplexObject
        Inherits EmployeeDataReference.StructuralObject
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EmployeeDataReference.IEmployeeDataService")>  _
    Public Interface IEmployeeDataService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmployeeDataService/Create", ReplyAction:="http://tempuri.org/IEmployeeDataService/CreateResponse")>  _
        Function Create(ByVal byteArrayEmp() As Byte) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmployeeDataService/Update", ReplyAction:="http://tempuri.org/IEmployeeDataService/UpdateResponse")>  _
        Function Update(ByVal bytEmployee() As Byte) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmployeeDataService/GetByID", ReplyAction:="http://tempuri.org/IEmployeeDataService/GetByIDResponse")>  _
        Function GetByID(ByVal empid As Integer) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmployeeDataService/Delete", ReplyAction:="http://tempuri.org/IEmployeeDataService/DeleteResponse")>  _
        Function Delete(ByVal empid As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmployeeDataService/GetAll", ReplyAction:="http://tempuri.org/IEmployeeDataService/GetAllResponse")>  _
        Function GetAll() As EmployeeDataReference.SerializeEmployee()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmployeeDataService/GetAllTechs", ReplyAction:="http://tempuri.org/IEmployeeDataService/GetAllTechsResponse")>  _
        Function GetAllTechs() As EmployeeDataReference.SerializeEmployee()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IEmployeeDataServiceChannel
        Inherits EmployeeDataReference.IEmployeeDataService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EmployeeDataServiceClient
        Inherits System.ServiceModel.ClientBase(Of EmployeeDataReference.IEmployeeDataService)
        Implements EmployeeDataReference.IEmployeeDataService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Create(ByVal byteArrayEmp() As Byte) As Integer Implements EmployeeDataReference.IEmployeeDataService.Create
            Return MyBase.Channel.Create(byteArrayEmp)
        End Function
        
        Public Function Update(ByVal bytEmployee() As Byte) As Integer Implements EmployeeDataReference.IEmployeeDataService.Update
            Return MyBase.Channel.Update(bytEmployee)
        End Function
        
        Public Function GetByID(ByVal empid As Integer) As Byte() Implements EmployeeDataReference.IEmployeeDataService.GetByID
            Return MyBase.Channel.GetByID(empid)
        End Function
        
        Public Function Delete(ByVal empid As Integer) As Integer Implements EmployeeDataReference.IEmployeeDataService.Delete
            Return MyBase.Channel.Delete(empid)
        End Function
        
        Public Function GetAll() As EmployeeDataReference.SerializeEmployee() Implements EmployeeDataReference.IEmployeeDataService.GetAll
            Return MyBase.Channel.GetAll
        End Function
        
        Public Function GetAllTechs() As EmployeeDataReference.SerializeEmployee() Implements EmployeeDataReference.IEmployeeDataService.GetAllTechs
            Return MyBase.Channel.GetAllTechs
        End Function
    End Class
End Namespace
